#!/usr/bin/env node
// AUTO-GENERATED version injection for ccaudit.
// Reads apps/ccaudit/package.json and writes apps/ccaudit/src/_version.ts.
// Runs on prebuild and pretest hooks — do not call directly in normal workflows.

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const here = path.dirname(fileURLToPath(import.meta.url));
const pkgPath = path.resolve(here, '..', 'package.json');
const outPath = path.resolve(here, '..', 'src', '_version.ts');

const pkg = JSON.parse(await readFile(pkgPath, 'utf8'));
const version = pkg.version;
if (typeof version !== 'string' || version.length === 0) {
  throw new Error(
    `apps/ccaudit/package.json has invalid "version" field: ${JSON.stringify(version)}`,
  );
}

const content =
  '// AUTO-GENERATED by scripts/gen-version.mjs — do not edit by hand.\n' +
  '// Sourced from apps/ccaudit/package.json at build/test time.\n' +
  `export const CCAUDIT_VERSION = ${JSON.stringify(version)};\n`;

await mkdir(path.dirname(outPath), { recursive: true });
await writeFile(outPath, content, 'utf8');

console.log(`[gen-version] wrote ${outPath} (CCAUDIT_VERSION=${version})`);
